---
title: "assignment_2"
format: html
editor: visual
---

```{r}
#| label: setup
#| echo: false
#| output: false
library(tidyverse)
library(vtable)

```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
#| echo: false
hoyde <- modelr::heights
hoyde <- hoyde %>%
mutate(
bmi = weight * 0.4536/(height * 2.54/100)^2,
married = fct_collapse(
.f = marital,
married = "married",
other_level = "not married"
),
edu_fac = cut(
x = education,
breaks = c(0, 12, 14, 16, 21),
labels = c("not_hs", "not_cc", "not_col", "col_plus"),
right = FALSE
)
)
```

```{r}
#| echo: false
# Inntekt lik 0
hoydeZeroInc <- hoyde |>
filter(income == 0)
# «Normal» inntekt
hoydeNormInc <- hoyde |>
filter(income > 0 & income < 343830)
hoydeHighInc <- hoyde |>
filter(income == 343830)
```

```{r}
#| echo: false
hoyde |>
ggplot(
mapping = aes(
x = height,
y = income
)
) +
geom_jitter(
size = 1,
alpha = 0.40
) +
geom_smooth(
formula = y ~ x,
method = "lm",
colour = "black",
lwd = 0.75,
se = FALSE
)
```

```{r}
#| echo: false
hoydeNormInc |>
ggplot(
mapping = aes(
x = height,
y = income
)
) +
geom_jitter(
size = 1,
alpha = 0.40
) +
geom_smooth(
formula = y ~ x,
method = "lm",
colour = "black",
lwd = 0.75,
se = FALSE
)
```

```{r}
#| echo: false
meanHeightMale <- hoyde |>
filter(sex == 'male') %>%
select(height) |>
# konverterer en tibble med 3402 rekker og 1 kolonne
# til en vektor med 3402 elementer siden mean() forlanger en
# vektor som input
pull() |>
# finner gjennomsnittet av verdiene i vektoren
mean()
meanHeightFemale <- hoyde |>
filter(sex == 'female') %>%
select(height) |>
pull() |>
mean()
# standard deviation
sdHeightMale <- hoyde |>
filter(sex == 'male') |>
select(height) |>
pull() |>
sd()
sdHeightFemale <- hoyde |>
filter(sex == 'female') |>
select(height) |>
pull() |>
sd()
```

```{r}
#| echo: false
ggplot(hoydeNormInc, aes(
  x = edu_fac,
  y = income
)) +
  geom_jitter(alpha = 0.5) +
  geom_smooth(method = "lm")
```

```{r}
#| echo: false
ggplot(hoydeNormInc, aes(
  x = height,
  y = income
)
) +
geom_point() +
  facet_wrap(~edu_fac)

```

```{r}
na <- is.na(hoyde)
```

```{r}
#| echo: false
hoydeNormInc |>
  filter(!is.na(edu_fac)) |> 
ggplot(
mapping = aes(
x = edu_fac,
y = income,
colour = edu_fac
)
) +
geom_jitter(
size = 1,
alpha = 0.40
) +
geom_smooth(
method = "lm"
)
```

```{r}
#| echo: false
hoydeNormInc |>
  filter(!is.na(edu_fac)) |> 
ggplot(
mapping = aes(
x = edu_fac,
y = height,
colour = edu_fac
)
) +
geom_jitter(
size = 1,
alpha = 0.40
)
```

```{r}
#| echo: false
hoydeNormInc |>
  filter(!is.na(edu_fac)) |> 
ggplot(
mapping = aes(
x = height,
y = income,
colour = edu_fac
)
) +
geom_jitter(
size = 1,
alpha = 0.40
) +
  facet_wrap(~edu_fac)
```

```{r}
#| echo: false
hoydeZeroInc |>
st("sex")
```

```{r}
#| echo: false
hoydeHighInc |>
st("sex")
```

```{r}
#| echo: false
hoyde |> 
  st()
```

VIDERE

```{r}
#| echo: false
hoydeZeroInc |> 
  st(c("height", "edu_fac"))
```

```{r}
#| echo: false
hoydeNormInc |> 
  st(c("height", "edu_fac"))
```

```{r}
#| echo: false
hoydeHighInc |> 
  st(c("height", "edu_fac"))
```

```{r}
hoyde <- hoyde |> 
  mutate(
    income_class = case_when(
    income == 0 ~ "zeroinc",
    income > 0 & income < 343830 ~ "norminc",
    income >= 343830 ~ "highinc"
    ))
```

```{r}
hoyde |> 
  ggplot(mapping = aes(
    x = edu_fac,
    y = income,
    colour = income_class
  )) +
  geom_jitter(alpha = 0.2)
```

```{r}
ggplot() +
  geom_point(data = hoyde, mapping = aes(x = education, y = height, colour = factor(income_class)))
```

```{r}
hoydeNormInc |> 
  st(c("height", "education"))
```

```{r}
hoydeHighInc |> 
  st(c("height", "education"))
```

```{r}
hoydeZeroInc |> 
  st(c("height", "education"))
```
