<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>assignment_2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="assignment_2_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment_2_files/libs/quarto-html/quarto.js"></script>
<script src="assignment_2_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment_2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment_2_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment_2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment_2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment_2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment_2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment_2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="assignment_2_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="assignment_2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">assignment_2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="innledning" class="level1">
<h1>Innledning</h1>
<p>I denne oppgaven har vi sett på sammenhengen mellom utdanning og inntekt, høyde og inntekt, utdanning og høyde, fordeling mellom menn og kvinner i ulike inntektsgrupper i forhold til høyde, men også fordelingen mellom menn og kvinner. De ulike inntektsgruppene er nullinntekt (hoydeZeroInc), normalinntekt (hoydeNormInc), høyinntekt (hoydeHighInc).Videre ser vi på hvordan observasjoner i hoydeZeroInc og hoydeHighInc skiller seg ut i forhold til hoydeNormInc når det kommer til høyde og utdanning.</p>
<section id="litteraturgjennomgang" class="level2">
<h2 class="anchored" data-anchor-id="litteraturgjennomgang">Litteraturgjennomgang</h2>
<section id="utdanning-og-inntekt" class="level3">
<h3 class="anchored" data-anchor-id="utdanning-og-inntekt">Utdanning og inntekt</h3>
<p>Når det kommer til sammenheng mellom utdanning og inntekt, viser det seg at menn som ikke ble uteksaminert fra videregående en halv tomme (1,27 cm) kortere enn gjennomsnittet, og er mer enn en tomme (2,54 cm) kortere enn en gjennomsnittlig høyskoleutdannet mann <span class="citation" data-cites="Deaton&amp;Arora2009">(<a href="#ref-Deaton&amp;Arora2009" role="doc-biblioref">Deaton and Arora 2009</a>)</span>. Når det kommer til kvinner, er forskjellen litt mindre <span class="citation" data-cites="Deaton&amp;Arora2009">(<a href="#ref-Deaton&amp;Arora2009" role="doc-biblioref">Deaton and Arora 2009</a>)</span>.</p>
<p>Så hvorfor har høyere mennesker bedre utdanning og høyere inntekt?</p>
<p>Ifølge <span class="citation" data-cites="Case&amp;Paxson2008">Case and Paxson (<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">2008</a>)</span> så har høyere mennesker større mulighet for å ha nådd sitt fulle kognitive potensiale enn lavere personer. Alt henger sammen med barndommen og hvor godt ernært et barn er gjennom hele barndommen. I tillegg henger det sammen med om barnet har vært skånet for barnesykdommer som har hatt potensialet til å bremse utviklingen i forhold til høyde. Har ikke barnet vært sykt, så vil de nå voksenhøyden som ligger i genet deres <span class="citation" data-cites="Case&amp;Paxson2008">(<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">Case and Paxson 2008</a>)</span>. I tillegg nevner <span class="citation" data-cites="Case&amp;Paxson2008">Case and Paxson (<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">2008</a>)</span> at det er en sammenheng mellom utvikling kognitivt og fysisk. &nbsp;Det vil si at et barn som ikke har nådd sin fulle mulige høyde, har heller ikke utviklet sitt fulle kognitive potensiale. Det er nemlig barn som mangler full kognitiv utvikling som står for lavere utdanningsnivå og lavere inntekt i voksen alder <span class="citation" data-cites="Case&amp;Paxson2008">(<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">Case and Paxson 2008</a>)</span>.</p>
</section>
<section id="høyde-og-inntekt" class="level3">
<h3 class="anchored" data-anchor-id="høyde-og-inntekt">Høyde og inntekt</h3>
<p>Når det kommer til forholdet mellom høyde og inntekt, har <span class="citation" data-cites="Deaton&amp;Arora2009">Deaton and Arora (<a href="#ref-Deaton&amp;Arora2009" role="doc-biblioref">2009</a>)</span> hentet data fra Gallup-Healthways Well-Being Index for å se på forholdet mellom høyde og inntekt. Ifølge <span class="citation" data-cites="Deaton&amp;Arora2009">Deaton and Arora (<a href="#ref-Deaton&amp;Arora2009" role="doc-biblioref">2009</a>)</span>, var menn som var over gjennomsnittlig høyde (177,8 cm) et trinn på stigen over menn som er under gjennomsnittlig høyde. For kvinner er forskjellen mindre. Kvinner under gjennomsnittlig høyde (162,6 cm) ligger litt mindre enn en tidel av et trinn under kvinner med over gjennomsnittlig høyde. Forskjellene kan virke små, men sammenlignet med faktorer som påvirker stigen, er inntekt en utgjørende faktor <span class="citation" data-cites="Deaton&amp;Arora2009">(<a href="#ref-Deaton&amp;Arora2009" role="doc-biblioref">Deaton and Arora 2009</a>)</span>. Øker vi høyden med en ekstra tomme på den såkalt stigen med effekten av en endring i inntekt, så vil hver ekstra tomme høyde ha samme effekt som en økning på 3,8% i familie inntekt for kvinner og 4,4% økning for menn.</p>
</section>
<section id="utdanning-og-høyde" class="level3">
<h3 class="anchored" data-anchor-id="utdanning-og-høyde">Utdanning og høyde</h3>
<p>Ifølge <span class="citation" data-cites="Case&amp;Paxson2008">Case and Paxson (<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">2008</a>)</span>, er det sammenheng mellom utdanning og høyde som fører til økt inntekt. Dette skyldes at høyere mennesker har større sannsynlighet for å ha nådd sitt fulle kognitive potensial enn lavere personer <span class="citation" data-cites="Case&amp;Paxson2008">(<a href="#ref-Case&amp;Paxson2008" role="doc-biblioref">Case and Paxson 2008</a>)</span>.</p>
<p>The <code>echo: false</code> option disables the printing of code (only output is displayed).</p>
</section>
</section>
<section id="eda-av-datasettet-heights-med-utgangspunkt-i-sammenheng-mellom-utdanning-og-inntekt" class="level2">
<h2 class="anchored" data-anchor-id="eda-av-datasettet-heights-med-utgangspunkt-i-sammenheng-mellom-utdanning-og-inntekt">EDA av datasettet heights med utgangspunkt i sammenheng mellom utdanning og inntekt</h2>
<p>Datasettet er kalt heights og er en del av pakken modelr, Wickham (2020), som er en utvidelspakke for statistikksystemet R, R Core Team (2021). Vi skal nå gjennomføre en EDA av datasettet med utgangspunkt i vår problemstilling som er sammenhengen mellom utdanning og inntekt ved bruk av kategorivariabel edu_fac:</p>
<ul>
<li>not_hs: 0-11 års utdanning</li>
<li>not_cc: 11-14 års utdanning</li>
<li>not_col: 14-16 års utdanning</li>
<li>col_plus: 16-21 års utdanning</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="assignment_2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vi ser at det er en sammenheng mellom inntekt og utdannelse. I figuren over ser vi at den linære regresjonslinjen viser en økning i inntekt for gitt lenger utdanning.</p>
<p>Videre skal vi ved hjelp av fasetter se på om det finnes en sammenheng mellom høyde og inntekt i forhold til hvilken utdanningsgruppe man er i.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="assignment_2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Av fasettene ser man at de ulike utdanningsgruppene reagerer ulikt på hvordan høyde påvirker hvilke inntekt man har. Vi kan se av den linjere regresjonslinjen i de ulike farsettene at en lavere utdannelsegruppe har et lavere “startpunkt” for inntekt, hvor dette gradvis øker om man er høyere.</p>
<p>Det som skiller seg mest klart ut i de fire fasetene er at “not_hs” har en relativt flat linjer regresjonslinje, som tolkes til at dersom man ikke har fullført high school vil ikke man øke markant i inntekt dersom man er høyere.</p>
<p>Vi ser også at i utdanningsgruppen “col_plus” er stigningstallet til den linjere regresjonslinjen brattere, og kan tolkes til at dersom man i denne katogorivariabelen vil man ha en større økning i inntekt i forhold til økning i høyde.</p>
<p>Ser man på de to gjennverende katogorivariablene “not_cc” og “not_col” skiller ikke disse linjære regrisjonslinjene seg betraktelige fra hverandre i forhold til at man øker i inntekt gitt at man øker i høyde. Man ser av disse variablene at det er en økning i inntekt dersom man er høyere utdannet.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="assignment_2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Fordelingen av menn &amp; kvinner “hoydeZeroInc”</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">1740</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">... male</td>
<td style="text-align: left;">745</td>
<td style="text-align: left;">43%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">... female</td>
<td style="text-align: left;">995</td>
<td style="text-align: left;">57%</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Fordelingen av menn &amp; kvinner “hoydehighInc”</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">143</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">... male</td>
<td style="text-align: left;">131</td>
<td style="text-align: left;">92%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">... female</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">8%</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Plottet under er en illustrasjon av hvilke innktekt “highinc”, “norminc” og “zeroinc” har, hvor vi skal videre se på hvilke andel menn &amp; kvinner som utgjør de ulike innteksgruppene.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="assignment_2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I fordelingen “hoydeHighInc” ser man et markant skille i fordelingen i menn og kvinner. Menn utgjør 92% av fordelingen “hoydeHighInc”, mens kvinner utgjør 8% av fordelingen.</p>
<p>I fordelingen “hoydeZeroInc” ser man at fordelingen mellom kvinner og menn er 43% menn og 57% Kvinner som utgjør fordelingen.</p>
<p>Plottet under er ment som en ildustrasjon av hvordan “hoydeHightInc”(rød), “hoydeZeroInc”(blå) skiller seg fra “hoydeNormInc” med utgangspunkt i høyde &amp; utdanning. Dette plottet er ikke 100% representativt for fordelingene ettersom man ikke får plottet alle observarsjonene, men fungerer godt som en indikator for å vise skille i utdanning &amp; høyde. Man ser at dersom man er i fordelingen “hoydeZeroInc” skorer majoriteten av observasjonene lavest på utdanning &amp; høyde, mens man i “hoydeNormInc” skorer en større del av observasjonene høyere på utdanning &amp; høyde enn “hoydeZeroInc”. Når det kommer til “hoydeHighInc” skorer denne klarest høyst på utdanning &amp; høyde. Vi vil seinere i oppgaven se nærmere på dette i faktiske tall.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment_2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 25</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 75</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">height</td>
<td style="text-align: left;">5123</td>
<td style="text-align: left;">67</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;">80</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: left;">5121</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">2.5</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">5123</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">... male</td>
<td style="text-align: left;">2526</td>
<td style="text-align: left;">49%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">... female</td>
<td style="text-align: left;">2597</td>
<td style="text-align: left;">51%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>I fordelingen “hoydeNormInc” ser man at man totalt har 5123 observasjoner med 2 NA verdier i forhold til utdanning. Denne fordelingen har klart mest observasjoner som er naturlig for et slikt datasett. Vi kan lese ut av tabellen over at i denne fordelingen er gjennomsnittshøyden 67 tommer eller 170.18cm, mens gjennomsnittlig utdanningsnivå er 13år.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 25</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 75</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">height</td>
<td style="text-align: left;">143</td>
<td style="text-align: left;">71</td>
<td style="text-align: left;">3.1</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">69</td>
<td style="text-align: left;">72</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: left;">143</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">2.4</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">143</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">... male</td>
<td style="text-align: left;">131</td>
<td style="text-align: left;">92%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">... female</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">8%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>I fordelingen “hoydeNormInc” ser man at man totalt har 143 observasjoner. Denne fordelingen har klart minst observasjoner av naturlige årsaker. Vi kan lese ut av tabellen over at i denne fordelingen er gjennomsnittshøyden 71 tommer eller 180.34cm med et standaravvik på 3.1 tommer eller 7.874cm, mens gjennomsnittlig utdanningsnivå er 17år med et standaravvik på 2.4år.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 25</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Pctl. 75</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">height</td>
<td style="text-align: left;">1740</td>
<td style="text-align: left;">66</td>
<td style="text-align: left;">4.1</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">69</td>
<td style="text-align: left;">84</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: left;">1732</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">2.4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">1740</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">... male</td>
<td style="text-align: left;">745</td>
<td style="text-align: left;">43%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">... female</td>
<td style="text-align: left;">995</td>
<td style="text-align: left;">57%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>I fordelingen “hoydeZeroInc” ser man at man totalt har 1740 observasjoner, med 8 NA verdier tilknyttet utdanning. Vi kan lese ut av tabellen over at i denne fordelingen er gjennomsnittshøyden 66 tommer eller 167.64cm med et standaravvik på 4.1 tommer eller 10.414cm, mens gjennomsnittlig utdanningsnivå er 12år med et standaravvik på 2.4 år.</p>
<p>Ser man da tilbake på plottet som ble presantert lengre oppe ser man at med faktiske tall vil plottet være representativt. “hoydeHightInc” skiller seg i den forstand fra “hoydeNormInc” i forhold til utdanning &amp; høyde at man er høyere utdannet og høyere. Man er i “hoydeHighInc” 10,16 cm høyere og 4 år høyere utdannet enn “hoydeNormInc” gjennomsnittslig. Når det kommer til “hoydeZeroInc” skiller dette seg fra “hoydeNormInc” i den forstand at man gjennomsnittslig er 2,54cm lavere og 1 år lavere utdannet.</p>
<p>Vi kan med utgangspunkt i disse observarsjonene sett vekk i fra andre faktorer se at utdanning &amp; høyde har en innvirkning på hvilke inntekt mann har. Høyere høyde &amp; utdanning vil gi en effekt i økt inntekt. .</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Case&amp;Paxson2008" class="csl-entry" role="listitem">
Case, Anne, and Christina Paxson. 2008. <span>“<span>Stature and Status: Height, Ability, and Labor Market Outcomes. | Journal of Political Economy | EBSCOhost</span>.”</span> https://openurl.ebsco.com/contentitem/doi:10.1086%2F589524?sid=ebsco:plink:crawler&amp;id=ebsco:doi:10.1086%2F589524.
</div>
<div id="ref-Deaton&amp;Arora2009" class="csl-entry" role="listitem">
Deaton, Angus, and Raksha Arora. 2009. <span>“Life at the Top: <span>The</span> Benefits of Height.”</span> <em>Economics &amp; Human Biology</em> 7 (2): 133–36.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>